name: Build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
    - name: Setup Java
      uses: actions/setup-java@v5.2.0
      with:
        java-version: '21'
        distribution: temurin
    - name: Build
      run: ./gradlew check
      shell: bash
    - name: Tag automerge branch
      if: github.event_name == 'pull_request'
      uses: TimonVS/pr-labeler-action@v5.0.0
      with:
        configuration-path: .github/pr-labeler.yml
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_PUBLIC_REPO_RELEASE_TRIGGERING }}